In [ ]:
for x in "banana":
  print(x)

b
a
n
a
n
a


In [ ]:
a = "Hello, World!"
print(len(a))

13


In [ ]:
txt = "The best things in life are free!"
print("free" in txt)

True


In [ ]:
txt = "The best things in life are free!"
print("expensive" not in txt)

True


In [ ]:
txt = "The best things in life are free!"
if "expensive" not in txt:
  print("No, 'expensive' is NOT present.")

No, 'expensive' is NOT present.


In [ ]:
b = "Hello, World!"
print(b[2:5])
print(b[0:5])
print(b[:5])
print(b[2:])

llo
Hello
Hello
llo, World!


In [ ]:
b="apple"
print(b[-3])
print(b[-4])
print(b[-5])

p
p
a


In [ ]:
a = "Hello, World!"
print(a.replace("H", "J"))

Jello, World!


In [ ]:
quantity = 3
itemno = 567
price = 49.95
myorder = "I want to pay {2} dollars for {0} pieces of item {1}."
print(myorder.format(quantity, itemno, price))

I want to pay 49.95 dollars for 3 pieces of item 567.


In [ ]:
def Cal(n):
  def Mult(x):
    return x * n
  return Mult

In [ ]:
import calender
print(calender.leapdays(2015,2018))

ModuleNotFoundError: No module named 'calender'

In [ ]:
def mycust():
  print("welcome")


In [ ]:
print("Hello")

Hello


In [ ]:
print("Hello")

Hello


In [ ]:
print("Hello")

Hello


In [ ]:
println("Hello")

NameError: name 'println' is not defined

In [ ]:
import numpy as np
PyArr=np.array([1,10,11,15,21])
PyEle = np.searchsorted (PyArr, 17)
print(PyEle)

4


In [ ]:
print("Hello")

Hello


In [ ]:
import numpy as np
PyArr=np.array([[1,2], [3,4],[5,6]])
print(PyArr)
PyArr[[0],[1]]+=1
PyArr[[1],[1]]+=1
PyArr[[2],[1]]+=3
print(PyArr)

[[1 2]
 [3 4]
 [5 6]]
[[1 3]
 [3 5]
 [5 9]]


In [ ]:
print("Hello")

Hello


In [ ]:
import numpy as np
PyArr1 = np.array([1,4],[3,1])
PyArr2 = np.array([4,5],[6,5])
print(PyArr1)
print(PyArr2)
PyArr3 = np.dot(PyArr1, PyArr2)
print(PyArr3)

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [ ]:
import numpy as np
PyArr1 = [-1.90,-2.3,-0.6788,12.34]
PyArr2 = np.ceil(PyArr1)
print(PyArr2)

[-1. -2. -0. 13.]


In [ ]:
import numpy as np
PyArr = ['abbbbbxcccccyyysss', 'aattttdsxxxxcccc','aaxxxxcccutt', 'aaxxccxxdscz']
print (PyArr)
print (np.char.find(PyArr, 'xc'))

['abbbbbxcccccyyysss', 'aattttdsxxxxcccc', 'aaxxxxcccutt', 'aaxxccxxdscz']
[ 6 11  5  3]
